INSERT INTO APP_USERS (EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, CONTACT_NO, REG_DATE, REG_CODE, ACTIVE, USER_TYPE) VALUES ('USER@MENTORING.COM', 'password', 'User First Name', 'User Last Name', '0000', NULL, 'CODE', 1, 'USER');
INSERT INTO APP_USERS (EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, CONTACT_NO, REG_DATE, REG_CODE, ACTIVE, USER_TYPE, LINKEDIN_URL, YEARS_EXP, ZONE_ID) VALUES ('MENTOR@MENTORING.COM', 'password', 'Mentor First Name', 'Mentor Last Name', '+40000000', NULL, 'CODE', 1, 'MENTOR', 'http://linkedin.com', 2, 'America/Anchorage');
INSERT INTO APP_USERS (EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, CONTACT_NO, REG_DATE, REG_CODE, ACTIVE, USER_TYPE) VALUES ('ADMIN@MENTORING.COM', 'password', 'Admin First Name', 'Admin Last Name', '0000', NULL, 'CODE', 1, 'ADMIN');

INSERT INTO MENTOR_WORKING_TIMES (MENTOR_EMAIL, FROM_HOUR, TO_HOUR, DAY_OF_WEEK) VALUES ('MENTOR@MENTORING.COM', PARSEDATETIME('13:00', 'HH:MM'), PARSEDATETIME('15:00', 'HH:MM'), '1');
INSERT INTO MENTOR_WORKING_TIMES (MENTOR_EMAIL, FROM_HOUR, TO_HOUR, DAY_OF_WEEK) VALUES ('MENTOR@MENTORING.COM', PARSEDATETIME('13:00', 'HH:MM'), PARSEDATETIME('15:00', 'HH:MM'), '2');
INSERT INTO MENTOR_WORKING_TIMES (MENTOR_EMAIL, FROM_HOUR, TO_HOUR, DAY_OF_WEEK) VALUES ('MENTOR@MENTORING.COM', PARSEDATETIME('13:00', 'HH:MM'), PARSEDATETIME('15:00', 'HH:MM'), '3');

INSERT INTO TECHNOLOGIES (EMAIL, TECHNOLOGY) VALUES ('USER@MENTORING.COM', 'JAVA8');
INSERT INTO TECHNOLOGIES (EMAIL, TECHNOLOGY) VALUES ('USER@MENTORING.COM', 'ANGULAR2');
INSERT INTO TECHNOLOGIES (EMAIL, TECHNOLOGY) VALUES ('MENTOR@MENTORING.COM', 'JAVA8');
INSERT INTO TECHNOLOGIES (EMAIL, TECHNOLOGY) VALUES ('MENTOR@MENTORING.COM', 'ANGULAR2');

INSERT INTO TRAININGS (ID, NAME, COST, MENTOR_ID) values  ('asdjkal-fdfs', 'Java 8 Training', 440, 'MENTOR@MENTORING.COM');
INSERT INTO TRAININGS (ID, NAME, COST, MENTOR_ID) values  ('asdjkal-fdfd', 'Angular 2 Training', 500, 'MENTOR@MENTORING.COM');

INSERT INTO TRAINING_ENROLLED values ('asdjkal-fdfs', 'USER@MENTORING.COM');

INSERT INTO TECHNOLOGY values ('JAVA8');
INSERT INTO TECHNOLOGY values ('ANGULAR2');
INSERT INTO TECHNOLOGY values ('SQL');