INSERT INTO APP_USERS (EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, CONTACT_NO, REG_DATE, REG_CODE, ACTIVE, USER_TYPE) VALUES ('ABC@ABC.COM', 'B', 'C', 'D', 'E', NULL, 'CODE', 1, 'USER');
INSERT INTO TRAININGS (ID, NAME, COST) values  ('asdjkal-fdfs', 'First Training', 44);
INSERT INTO TRAININGS (ID, NAME, COST) values  ('asdjkal-fdfd', 'Second Training', 500);